### ISSUE TITLE
Offline install not working

### ISSUE THREAD

**Issue by harryjohnston** [R-ArcGIS/r-bridge-install#21]
The offline install option isn't working.  The problem appears to be that the call to release_info() never returns, i.e., calls sys.exit() instead of returning None as install_package.py seems to expect.

Output:

```
Executing: InstallBindings false
Start Time: Thu May 26 16:19:05 2016
Running script InstallBindings...
Failed to download 'https://api.github.com/repos/R-ArcGIS/r-bridge/releases/latest', error: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Completed script InstallBindings...
Failed to execute (InstallBindings).
Failed at Thu May 26 16:19:26 2016 (Elapsed Time: 21.14 seconds)

```

**Comment by puzzledkiwi** [comment]
I'm also having this problem, although I can't weigh in on the python. 

Output:
`Executing: InstallBindings false
Start Time: Wed Jun 01 12:31:23 2016
Running script InstallBindings...
Failed to download 'https://api.github.com/repos/R-ArcGIS/r-bridge/releases/latest', error: [Errno 10061] No connection could be made because the target machine actively refused it.
Completed script InstallBindings...
Failed to execute (InstallBindings).
Failed at Wed Jun 01 12:31:24 2016 (Elapsed Time: 1.11 seconds)`

**Comment by scw** [comment]
Thanks for the report, @harryjohnston and @puzzledkiwi. I'll take a look.

**Comment by scw** [comment]
Hello @harryjohnston and @puzzledkiwi,

This should now be resolved with commits https://github.com/R-ArcGIS/r-bridge-install/commit/a2673974146b3069b8af622b0b1748a338cff499 and https://github.com/R-ArcGIS/r-bridge-install/commit/a912f06a5debf854c9071e7b16bc86643d0f7d7a. Let us know if this solves your problem and you can use offline installation from within the toolbox.

**Comment by puzzledkiwi** [comment]
It works! Thank you so much for the fix!


Executing: InstallBindings false
Start Time: Wed Jun 22 11:08:03 2016
Running script InstallBindings...
Unable to access'https://api.github.com/repos/R-ArcGIS/r-bridge/releases/latest', error: [Errno 10061] No connection could be made because the target machine actively refused it.
Unable to get current release information. Trying offline installation.
Found local copy of binding, installing from zip
Rcmd.exe INSTALL c:\users\r303977\appdata\local\temp\arc41ff\tmpdhohvt\arcgisbinding_1.0.0.119.zip
package 'arcgisbinding' successfully unpacked and MD5 sums checked
* installing to library 'C:/Program Files/R/R-3.2.2/library'
R package path: C:\Program Files\R\R-3.2.2\library\arcgisbinding.
ArcGIS 10.3.1 detected. Creating link to package.
Completed script InstallBindings...
Succeeded at Wed Jun 22 11:08:07 2016 (Elapsed Time: 3.67 seconds)

**Comment by scw** [comment]
Glad to hear it @puzzledkiwi! I'll close this issue for now, but feel free to open a new one if you have issues or questions.

Cheers, Shaun
