### ISSUE TITLE
R  Bindings Installation in ArcGIS Pro fails

### ISSUE THREAD

**Issue by Jololi** [R-ArcGIS/r-bridge-install#51]
When I run the Install R bindings script in ArcGIS Pro, I receive the following message:  

_Unable to locate requested R command: C:\Program Files\R\R.3.3.2.2\bin\x64\Rscript.exe_  

The problem is that in my Program Files folder, I have two R folders: one for R-3.3.2 and one for 3.3.2.2.
In the former (3.3.2), Rscript.exe is effectively located in the x64 folder.
But in the second (3.3.2.2), it is located in the i386 folder. And it looks like the Install R binding tool is looking for Rscript.exe in a place where it doesn't exist.

Thanks for your help.

**Comment by scw** [comment]
@Jololi, the installer uses the registry to try and find the correct location to install R into. If you can, I'd uninstall and reinstall R, installing both the 32-bit and 64-bit versions at the same time. Best I know, there isn't an R 3.3.2.2 release, so that's probably just an error that crept in during a previous install. If you know that the version in 3.3.2.2 is correct and what you'd like to use, alternatively you could set the `R_HOME` variable to point at the location of the R installation directory you'd like to use.

**Comment by Jololi** [comment]
Hello Shawn, 
Thanks you so much. I uninstalled R and then deleted the 3.3.2.2 folder (I have no idea how it was installed!). Then I reinstalled and this time the R Bindings installation succeeded. 
I appreciate your help. 
Best regards.
