### ISSUE TITLE
R-ArcGIS/r-bridge-install 

### ISSUE THREAD

**Issue by jfpeters** [R-ArcGIS/r-bridge-install#52]
![capture](https://user-images.githubusercontent.com/31742378/30178005-8d912208-93d5-11e7-835f-77b02a822c33.PNG)

I'm in the process of installing the R-bridge.  When connecting to the folder from ArcMap, the "toolbox" appears with a red X over - see attached snapshot.  

I'm using ArcMap 10.5, R 32-bit 3.2.0 and the R-bridge version listed under the "Code" heading of this site.  Thank you for any assistance you may be able to provide.  - James

**Comment by scw** [comment]
Hi James,

Thank you for the bug report, and I'm sorry to hear the installer isn't working for you. Could you right click on the toolbox, and select 'Check Syntax' and send on a screenshot of the resulting message?

Thanks, Shaun

**Comment by jfpeters** [comment]
Shaun,

See below,

[cid:image001.png@01D327F4.F152DF40]

Thanks!


James Peters
Senior Economic Analyst
Regional Planning Group

ITC
27175 Energy Way
Novi, MI  48377
248-946-3245 [work]
575-779-8990 [cell]
Fax: 248-946-3490
jpeters@itctransco.com<mailto:jpeters@itctransco.com>

**Comment by scw** [comment]
Hi James,

Unfortunately it looks like GitHub stripped the attachment to the thread. Could you visit the page https://github.com/R-ArcGIS/r-bridge-install/issues/52 and attach the image there directly? Thanks!

**Comment by jfpeters** [comment]
![capture](https://user-images.githubusercontent.com/31742378/30213121-9be02e12-9475-11e7-9678-297f7f89f6b2.PNG)

**Comment by jfpeters** [comment]
Thanks for looking into this!

**Comment by scw** [comment]
Hello James,

OK, what it looks like is that there are multiple Python installations on the machine. Typically, ArcGIS itself installs Python into the `C:\Python27\ArcGIS10.5` directory, so that it won't affect an existing installation in `C:\Python27`. Here, it looks like there is an installation at `C:\Python27`, and that installation also contains NumPy. Because there are now two different Python environments on your path, they may have conflicting versions of the Python packages, which prevents ArcGIS from loading its Python components. This will prevent most Geoprocessing tools from working on the machine, so I think it's worth trying to fix the issue rather than coming up with a workaround to install the bridge.

To fix the Python installation, you have a few options. If you know of another Python installation at C:\Python27, and don't currently use it, removing that additional installation should resolve this issue. It's likely listed under "add / remove program files" as a Python installation for version 2.7. If you don't know where that Python is coming from, or do need it for something else, a short-term fix would be to rename the Python27 folder, then try repairing the ArcGIS installation. That will cause the ArcGIS installer to lay down any files it needs into the `C:\Python27\ArcGIS10.5` directory, and installing the bridge should work fine from there. If that doesn't work, or you'd prefer not to affect the second Python install, I can walk you through modifying the environment variables to fix this.

Cheers,
Shaun

**Comment by jfpeters** [comment]
Shaun - I uninstalled and then reinstalled ArcMap.  That seemed to solve the issue.  Thanks!

**Comment by scw** [comment]
@jfpeters Great! Let us know if you have any other questions. I'll close this issue for now, but feel free to reopen it if you run into anything.

Cheers, Shaun
