### ISSUE TITLE
Issue using Arc Map 10.3.1

### ISSUE THREAD

**Issue by jjconnolly85** [R-ArcGIS/r-bridge-install#60]
Hi everyone
Can you please assist? I have been following the tutorial to get the bridge installed and this has worked however I am not sure how you point ArcMap to the tool?

All the demos use ArcPro. Is this bridge only usable with Pro or can you use it with ArcMap too? 

Any help would be greatly welcomed. So excited to be potentially using this soon. 

Thanks to the developers 

Regards 
James

**Comment by scw** [comment]
Hello @jjconnolly85,

Yes, the bridge works fine within ArcMap. We created the demos with ArcGIS Pro because it is our newer product, but it works just the same within 10.x &ndash; script tools can be R code, which will be executed like any other Geoprocessing tools.

For example, see the [sample tools](https://github.com/R-ArcGIS/r-sample-tools) which contain a few tools which perform real analysis operations. Those all work in both environments and are documented for both Pro and ArcMap.

If you have any specific questions or issues, feel free to follow up here.

Cheers, Shaun

**Comment by jjconnolly85** [comment]
Hi Shaun 
Thanks very much ch for the help. Really appreciate it. 

The issue I’m having relates to pointing ArcMap to the R directory. 

The instructions state that this should take place in ArcPro as per the below  

“Click Options. In the Options window, in the Application list, click geoprocessing In the R-ArcGIS Support section, select your desired R home directory.”

I can’t get to this stage in ArcMap. 

Apologies if this seems like a very basic issue. 

Kind regards

James

**Comment by scw** [comment]
@jjconnolly85 Hopefully @marpobuda's answer over email gets you started in the right direction. We'll be releasing an updated website in the coming months which should clarify the installation process depending on the environment you're in.

**Comment by gdg100** [comment]
I have problems with arcmap 10.3.1 because it can not load the R libraries  (ver 3.4.3) that I installed with RStudio (ver 1.1.419) and arcgisbinding (ver 1.0.0.128). The toolbox always stops with the following examples, and not only, which are implemented in the "r-bridge-master" tool, ie with the following R scripts: logreg, qqplot, sp_geometry etc. I believe that ARCMAP is not able to connect to the R library

The typical error message is as follows (R script  sp_geometry):

_Executing: logreg2 ca_ozone_pts X
Running script logreg2...
Installing package into 'C:/Users/giuseppe/Documents/R/win-library/3.4'
(as 'lib' is unspecified)
trying URL 'http://cran.cnr.Berkeley.edu/bin/windows/contrib/3.4/sp_1.2-7.zip'
Content type 'application/zip' length 1538824 bytes (1.5 MB)
downloaded 1.5 MB
package 'sp' successfully unpacked and MD5 sums checked
The downloaded binary packages are in
	C:\Users\giuseppe\AppData\Local\Temp\RtmpErPvgZ\downloaded_packages
**Error in value[[3L]] : package or namespace load failed for 'sp' in inDL(x, as.logical(local), as.logical(now), ...): unable to load shared object '**C:/Program Files/R/R-3.4.3/library/stats/libs/i386/stats.dll'**:
  LoadLibrary failure:**  Impossibile trovare il modulo specificato.
Failed to execute (logreg2).

**Comment by dpavlushko** [comment]
To solve "stats.dll" loading issue on R 3.4.3 you need to add `C:/Program Files/R/R-3.4.3/bin/i386` to the `PATH` environment and restart ArcMap. (For 64 bit ArcGISPro add `..../bin/x64`)
Second solution is to install Beta version of the 'arcgisbinding' package [https://github.com/R-ArcGIS/r-bridge/releases/tag/v1.0.1.229-beta](https://github.com/R-ArcGIS/r-bridge/releases/tag/v1.0.1.229-beta)

**Comment by gdg100** [comment]
I apologize for my insistence but how can I add C:/Program Files/R/R-3.4.3/bin/i386 to the PATH environment?

**Comment by gdg100** [comment]
in any case the PATH environment of ArcMap?

**Comment by dpavlushko** [comment]
Use Windows settings like this:
![image](https://user-images.githubusercontent.com/12039804/36128980-d785229a-1019-11e8-8993-5d2a8531621a.png)

**Comment by gdg100** [comment]
I changed the path environment  by following the instructions you showed me
and now it works perfectly! Thank you very much

2018-02-13 2:26 GMT+01:00 Dmitry Pavlushko <notifications@github.com>:

**Comment by scdub** [comment]
Closing this as it references older versions of R and the installer that have since been resolved.
