### ISSUE TITLE
Offline Installation

### ISSUE THREAD

**Issue by ruckc** [R-ArcGIS/r-bridge-install#7]
It would be nice if this tool supported offline installation.

**Comment by ruckc** [comment]
This is fairly frustrating... your install_package.py's install_package function isn't even broken out into fetch_package and install_package and symlink_package.  I sarcastically love the assumption of constant, always on full internet connectivity.  You don't even define internet connectivity as a prerequisite to using this installation.

**Comment by scw** [comment]
I've added internet connectivity as a prerequisite in the README. We don't currently have offline installation instructions, particularly because for most users in most environments, they need to install R packages to use the bridge effectively, and we haven't yet approached that problem in a holistic fashion (e.g. how to allow our users to fully use R in an offline environment).

That said, you don't need this package to start using R from ArcGIS. You can manually download [the package release](https://github.com/R-ArcGIS/r-bridge/releases), install the included `arcgisbinding` package into your R environment, and you should be good from there. This package itself is intended to simplify the installation process for less technical users.

**Comment by scw** [comment]
FIxed the offline installation use-case, let me know if you have further issues or problems.
