### ISSUE TITLE
arcgisbinding installed but arctoolbox not recognizing

### ISSUE THREAD

**Issue by DanStrobridge** [R-ArcGIS/r-bridge-install#75]
R 3.5.0 and desktop 10.5.1.  R integration python scripts install/version scripts output suggest it installed correctly but my arctoolbox tool gives:
*** Please install ArcGIS R integration package

I've got Rstudio referencing 32-bit version of R and arc.check_product suggests it's working correctly:
>   arc.check_product()
product: ArcGIS Desktop ( 10.5.1.7333 )
license: Advanced 
version: 1.0.1.232

full output of R installation details:
Executing: RInstallDetails
Start Time: Sat Aug 25 09:52:29 2018
Running script RInstallDetails...
R (version 3.5.0), installed in: C:\Program Files\R\R-3.5.0
R packages will be installed into: C:\Users\strobrid\R\win-library\3.5
All R package libraries detected: C:\Users\strobrid\R\win-library\3.5;C:\Program Files\R\R-3.5.0\library
The ArcGIS R package (version 1.0.1.232) is installed at: C:\Users\strobrid\R\win-library\3.5\arcgisbinding
Completed script RInstallDetails...
Succeeded at Sat Aug 25 09:52:29 2018 (Elapsed Time: 0.03 seconds)

**Comment by DanStrobridge** [comment]
I installed R 3.5.1 and installed the package there but no luck.  However, I solved my issue by copying the arcgisbinding package from the C:\Users\<username>\R\win-library location to the C:\Program Files\R\R-3.5.1\library directory.

**Comment by scw** [comment]
@DanStrobridge Glad you were able to resolve this yourself -- I think the issue is desktop checks a few standard locations, and the default per-user library directory is `%USERPROFILE%\Documents\R\win-library\3.5`, on your machine it looks like its configured to be directly in your home folder instead of within Documents. Is this set up via `R_LIBS_USER`? Thanks, Shaun
