### ISSUE TITLE
Issue when installing R bindings/R-ArcGIS Bridge (ArcGIS 10.5.1; R x64 3.6.1)

### ISSUE THREAD

**Issue by Maik-SPW** [R-ArcGIS/r-bridge-install#85]
I receive the following error message when trying to install R bindings (ArcGIS 10.5.1; R x64 3.6.1)

Can anyone help!? Many thanks.

![Install_R_bindings](https://user-images.githubusercontent.com/55180947/64680044-43806800-d47d-11e9-80f5-b20696bd0658.png)

**Comment by scdub** [comment]
Hello @Maik-SPW,

Because ArcMap is a 32-bit application, you'll need to have a 32-bit version of R if you want to use it from within Pro. When you run the R installer, it should let you select the 32-bit (or i386) version of the installation along with the 64-bit (or x64) version. Once the 32-bit version is installed, you can still use the 64-bit version via background geoprocessing, see [this diagram for details](https://raw.githubusercontent.com/R-ArcGIS/r-bridge-install/master/img/version-block-detailed.png).

**Comment by scdub** [comment]
@Maik-SPW were you able to resolve this issue by installing the 32-bit version of R? Thanks for letting us know either way.
