### ISSUE TITLE
Issues installing r-bridge with R 3.6.1 and arcMap 10.6.1

### ISSUE THREAD

**Issue by AbernethyR** [R-ArcGIS/r-bridge-install#86]
HI, I have been working on this for quite a while with no luck (and am no slightly worried i have mucked it up beyond repair).  

I initially installed the bridge and arcgisbinding without RTools, so deleted, installed tools and reinstalled.  

In arcCat I at first had luck installing the bridge, but now get this error message 

I also have arcPro installed on this machine, but am not using it just yet.  My intent is to use the bridge to access sde database files...

![2019-10-25_15-37-39](https://user-images.githubusercontent.com/57020070/67606998-48089380-f740-11e9-81df-b6ce56fc5127.png)

HELP!!  Thanks, R

**Comment by AbernethyR** [comment]
Further trouble shooting discovered this error....
![2019-10-25_16-10-12](https://user-images.githubusercontent.com/57020070/67607519-ff51da00-f741-11e9-83f7-514b29ccfdbc.png)

**Comment by scdub** [comment]
@AbernethyR Thanks for the report. The error you get in your first message is unexpected, since `arcpy.GetInstallInfo()` is a basic functionality that ArcPy provides -- my guess is, something is interfering with the Python installation (perhaps from another software product), but if you have Pro co-installed on the machine, there is a simpler way to get the bridge for both environments. You can [follow the instructions in this video](https://community.esri.com/videos/4136-installing-the-r-arcgis-bridge-for-arcgis-pro-20) to install the bridge into R for both Pro and ArcMap, and that'll be easier than trying to do it using this toolbox.

Cheers, Shaun

**Comment by AbernethyR** [comment]
Thanks - this worked!
