### ISSUE TITLE
trouble with r-bridge-install on ArcGIS 10.6.1 R3.6.1

### ISSUE THREAD

**Issue by AnnetteVDD** [R-ArcGIS/r-bridge-install#88]
When I run InstallR bindings I get this error:

Executing: InstallBindings true 3.6.1
Running script InstallBindings...

Traceback (most recent call last):
  File "<string>", line 233, in execute
  File "C:\Users\annettew\Downloads\r-bridge-install-master\rtools\install_package.py", line 202, in install_package
    download_url = release_info()[0]
  File "C:\Users\annettew\Downloads\r-bridge-install-master\rtools\github_release.py", line 89, in release_info
    json_r = parse_json_url(latest_url)
  File "C:\Users\annettew\Downloads\r-bridge-install-master\rtools\github_release.py", line 71, in parse_json_url
    url, e.reason)
AttributeError: 'exceptions.LookupError' object has no attribute 'reason'

Failed to execute (InstallBindings).

What can I do?

**Comment by scdub** [comment]
@AnnetteVDD I've put up a new version which should provide a more useful error -- but it looks like the script is failing to download the file from github. This is likely happening because software on your machine is preventing ArcMap and Python from downloading files. In that case, you can manually download the zip file from:
  https://github.com/R-ArcGIS/r-bridge/releases/tag/v1.0.1.237

If you copy that zip file into the same directory as the Python toolbox, it should be detected and allow you to install it.

Cheers,
Shaun

**Comment by AnnetteVDD** [comment]
@scdub  That worked like a charm. Thanks a lot!

Annette

**Comment by scdub** [comment]
@AnnetteVDD Great! Happy to help, let us know if you have any other issues.
